config/routes.rb
Gestor::Application.routes.draw do

  get "sphinx/contacto"
  resources :empresas

  resources :personas

  get "home/index"

  resources :proyectos do
  	resources :objetivo_negocios
  	resources :milestones
  end

   root :to => "home#index"

end

app/models/charter.rb
class Charter < ActiveRecord::Base
	has_many :objetivo_negocios, :dependent => :destroy
	has_many :charter_contactos
	has_many :contactos, :through => :charter_contactos	
	belongs_to :proyecto
	
	accepts_nested_attributes_for :charter_contactos, :allow_destroy => true
end

app/models/charter_contacto.rb
class CharterContacto < ActiveRecord::Base

  ROLES = ['Sponsor', 'Preparado por', 'Cliente', 'Administrador de programa', 'Lider de Proyecto'].sort!

  belongs_to :charter
  belongs_to :contacto
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  belongs_to :contactable, :polymorphic => true
  belongs_to :identificable, :polymorphic => true
end

app/models/elemento_estrategico.rb
class ElementoEstrategico < ActiveRecord::Base
  belongs_to :objetivoNegocio
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_one :contacto, :as => :identificable
	
	
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :charter
end

app/models/objetivo_negocio.rb
class ObjetivoNegocio < ActiveRecord::Base
  belongs_to :charter
  has_many :elemento_estrategicos, :dependent => :destroy
  
  accepts_nested_attributes_for :elemento_estrategicos, :allow_destroy => true
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_one :contacto, :as => :identificable
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
	include Permalynkable
	extend Permalynkable::ClassMethods
	
	attr_accessible :delete_charter_doc, :delete_pert_file

	has_one :charter, :dependent => :destroy
	accepts_nested_attributes_for :charter
	
	has_attached_file :charter_doc
	has_attached_file :pert_file
	
	before_save :destroy_files?

	def delete_charter_doc
    	@image_delete ||= "0"
	end

	def delete_charter_doc=(value)
		@image_delete = value
	end
	
	def delete_pert_file
    	@image_delete ||= "0"
	end

	def delete_pert_file=(value)
		@image_delete = value
	end

	private
		def destroy_files?
			self.charter_doc.clear if @delete_charter_doc == "1"
			self.pert_file.clear if @delete_pert_file == "1"
		end
	
end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base

  ROLES = ['Patrocinador', 'Elaborado por', 'Autorizado por','Cliente', 'Lider de Proyecto']

  belongs_to :user
  belongs_to :charter
  has_one :contacto, :as => :contactable
end

app/controllers/charters_controller.rb
class ChartersController < ApplicationController
  # GET /charters
  # GET /charters.xml
  def index
    @charters = Charter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @charters }
    end
  end

  # GET /charters/1
  # GET /charters/1.xml
  def show
    @charter = Charter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @charter }
    end
  end

  # GET /charters/new
  # GET /charters/new.xml
  def new
    @charter = Charter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @charter }
    end
  end

  # GET /charters/1/edit
  def edit
    @charter = Charter.find(params[:id])
  end

  # POST /charters
  # POST /charters.xml
  def create
    @charter = Charter.new(params[:charter])

    respond_to do |format|
      if @charter.save
        format.html { redirect_to(@charter, :notice => 'Charter was successfully created.') }
        format.xml  { render :xml => @charter, :status => :created, :location => @charter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @charter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /charters/1
  # PUT /charters/1.xml
  def update
    @charter = Charter.find(params[:id])

    respond_to do |format|
      if @charter.update_attributes(params[:charter])
        format.html { redirect_to(@charter, :notice => 'Charter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @charter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /charters/1
  # DELETE /charters/1.xml
  def destroy
    @charter = Charter.find(params[:id])
    @charter.destroy

    respond_to do |format|
      format.html { redirect_to(charters_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  # GET /proyectos
  # GET /proyectos.xml
  def index
    @proyectos = Proyecto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @proyectos }
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.xml
  def show
    @proyecto = Proyecto.exfind(params[:id])
	@charter = @proyecto.charter
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @proyecto }
    end
  end

  # GET /proyectos/new
  # GET /proyectos/new.xml
  def new
    @proyecto = Proyecto.new
    @proyecto.charter = Charter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @proyecto }
    end
  end

  # GET /proyectos/1/edit
  def edit
    @proyecto = Proyecto.exfind(params[:id])
  end

  # POST /proyectos
  # POST /proyectos.xml
  def create
    @proyecto = Proyecto.new(params[:proyecto])

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to(@proyecto, :notice => 'Proyecto was successfully created.') }
        format.xml  { render :xml => @proyecto, :status => :created, :location => @proyecto }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @proyecto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /proyectos/1
  # PUT /proyectos/1.xml
  def update
    @proyecto = Proyecto.exfind(params[:id])

    respond_to do |format|
      if @proyecto.update_attributes(params[:proyecto])
        format.html { redirect_to(@proyecto, :notice => 'Proyecto was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @proyecto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.xml
  def destroy
    @proyecto = Proyecto.exfind(params[:id])
    @proyecto.destroy

    respond_to do |format|
      format.html { redirect_to(proyectos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sphinx_controller.rb
class SphinxController < ApplicationController

  def contacto
  	if params[:q]
	  	_personas = Persona.includes(:contacto).where(['nombre LIKE :q OR ap_paterno LIKE :q OR ap_materno LIKE :q', {:q => "%#{params[:q]}%"}]).order('nombre').all
	  	@data = _personas.map{|x| x.attributes.merge({:contacto=>x.contacto.attributes}) }
	end
	
	respond_to do |format|
		format.json{ render :json=>@data.as_json }
	end
	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charters_helper.rb
module ChartersHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/sphinx_helper.rb
module SphinxHelper
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/proyectos/_form.html.erb
<%= simple_nested_form_for(@proyecto, :html=>{:class=>'form-horizontal'}) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.fields_for :charter do |charter_fields|%>
  	<%= render :partial=>'form_charter', :locals=>{:f => charter_fields} %>
  <% end %>
  

  
  <div class="form-actions">
    <%= link_to 'Cancelar', proyectos_path, :class=>'btn' %>
    <%= f.submit 'Guardar Proyecto', :class=>'btn btn-primary' %>
  </div>
<% end %>

app/views/proyectos/_form_charter.html.erb
<div class="field">
   <%= f.input :proyecto_titulo, :label=>'Título', :placeholder=>'Título', :input_html=>{:class=>'span5'} %>
</div>
<div class="field">
   <%= f.input :proyecto_version, :label=>'Versión', :placeholder=>'Versión', :input_html=>{:class=>'span5'} %>
</div>
<div class="field">
   <%= f.input :resumen, :input_html=>{:rows=>0, :cols=>nil, :class=>'span5'}, :label=>'Resumen ejecutivo', :placeholder=>'Resumen ejecutivo' %>
</div>
<div class="field">
	<%= f.fields_for :charter_contactos do |part_form| %>
		<%= render :partial=>'form_participantes', :locals=>{:f => part_form} %>
	<% end %>
	<legend><i class="icon-user" style="vertical-align:baseline;"></i> Participantes</legend>
	<p>
		<%= f.link_to_add :charter_contactos, 'data-toggle'.to_sym=>"modal", :class=>'btn pull-right' do %>
			<i class="icon-plus"></i>
			Agregar Participante
		<% end %>
	</p>
</div>

app/views/proyectos/_form_participantes.html.erb
<div class="well form-inline">
	<%= f.link_to_remove "x", :class=>'close' %>
	<br />
	<div class="control-group">
		<div class="controls input-prepend">
    		<%= link_to '#', :class=>'btn triggerFindContacto' do %>
				<i class='icon-book'></i>
			<% end %><%= text_field_tag :contacto_nombre, {}, :disabled=>'disabled', :class=>'disabled contacto_nombre' %>
			<%= f.input :contacto_id, :as=>'hidden' %>
		</div>
	</div>
	<%= f.input :role, :collection => CharterContacto::ROLES, :include_blank => false %>
</div>
<div class="modal hide fade" id="findContacto">
	 <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Buscar contacto</h3>
  </div>
  <div class="modal-body">
	<div class="input-append">
		<%= text_field_tag :q %><%= link_to url_for(:controller=>'sphinx', :action=>:contacto), {:remote => true, :class=>'btn submit_link'}  do %>
			<i class='icon-search'></i>
		<% end %>
	</div>
	<div>
		<br />
		<table id="query_contacts" class="table table-condensed">
			
		</table>
	</div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" rel="no-follow" data-dismiss="modal">Cerrar</a>
  </div>
</div>

app/views/proyectos/edit.html.erb
<h1>Editing proyecto</h1>

<%= render 'form' %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

app/views/proyectos/index.html.erb
<h1>Mis Proyectos</h1>
<%= link_to 'Agregar Proyecto', new_proyecto_path, :class=>'btn btn-primary pull-right' %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Descripcion</th>
    <th>Fecha Creación</th>
  </tr>
</thead>
 <tbody>
<% @proyectos.each do |proyecto| %>
  <tr>
    <td><%= link_to proyecto.charter.proyecto_titulo, proyecto %></td>
    <td><%= proyecto.created_at %></td>
    <td>
    	<div class="btn-group pull-right">
		<%= link_to '#', :class=>"btn dropdown-toggle", :'data-toggle'.to_sym=>"dropdown" do  %>
		    Acciones
    		<span class="caret"></span>
  		<% end %>
  		<ul class="dropdown-menu">
    		<li><%= link_to 'Editar', edit_proyecto_path(proyecto) %></li>
    		<li><%= link_to 'Eliminar', proyecto, :confirm => 'Are you sure?', :method => :delete %></li>
	 	</ul>
		</div>
	</td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/proyectos/new.html.erb
<h1>Nuevo Proyecto</h1>
<br />
<%= render 'form' %>

app/views/proyectos/show.html.erb
<h1>Mis proyectos <small><%= @proyecto.charter.proyecto_titulo %></small></h1>
<% if notice%>
<div class="alert alert-block">
  <a class="close" data-dismiss="alert">×</a>
  <p id="notice"><%= notice %></p>
</div>
<%end%>

<p>
  <b>Descripcion:</b>
  <%= @proyecto.descripcion %>
</p>

<p>
  <b>Proyecto titulo:</b>
  <%= @charter.proyecto_titulo %>
</p>

<p>
  <b>Proyecto version:</b>
  <%= @charter.proyecto_version %>
</p>

<p>
  <b>Resumen:</b>
  <%= @charter.resumen %>
</p>

<div class="form-actions">
	<%= link_to 'Regresar', proyectos_path, :class=>'btn' %>
	<div class="pull-right">
		<%= link_to 'Ver Objetivos', proyecto_objetivo_negocios_path(@proyecto), :class=>'btn' %>
		<%= link_to 'Editar', edit_proyecto_path(@proyecto), :class=>'btn' %>
		<%= link_to 'Eliminar', proyecto_path(@proyecto), :class=>'btn btn-danger', :confirm => 'Are you sure?', :method => :delete %>
	</div>
</div>