config/routes.rb
Gestor::Application.routes.draw do

  get "sphinx/contacto"
  resources :empresas

  resources :personas

  get "home/index"

  resources :proyectos do
  	resources :objetivo_negocios
  	resources :milestones
  end

   root :to => "home#index"

end

app/models/charter.rb
class Charter < ActiveRecord::Base
	has_many :objetivo_negocios, :dependent => :destroy
	has_many :charter_contactos
	has_many :contactos, :through => :charter_contactos	
	belongs_to :proyecto
	
	accepts_nested_attributes_for :charter_contactos, :allow_destroy => true
end

app/models/charter_contacto.rb
class CharterContacto < ActiveRecord::Base

  ROLES = ['Sponsor', 'Preparado por', 'Cliente', 'Administrador de programa', 'Lider de Proyecto'].sort!

  belongs_to :charter
  belongs_to :contacto
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  belongs_to :contactable, :polymorphic => true
  belongs_to :identificable, :polymorphic => true
end

app/models/elemento_estrategico.rb
class ElementoEstrategico < ActiveRecord::Base
  belongs_to :objetivoNegocio
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_one :contacto, :as => :identificable
	
	
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :charter
end

app/models/objetivo_negocio.rb
class ObjetivoNegocio < ActiveRecord::Base
  belongs_to :charter
  has_many :elemento_estrategicos, :dependent => :destroy
  
  accepts_nested_attributes_for :elemento_estrategicos, :allow_destroy => true
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_one :contacto, :as => :identificable
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
	include Permalynkable
	extend Permalynkable::ClassMethods
	
	attr_accessible :delete_charter_doc, :delete_pert_file

	has_one :charter, :dependent => :destroy
	accepts_nested_attributes_for :charter
	
	has_attached_file :charter_doc
	has_attached_file :pert_file
	
	before_save :destroy_files?

	def delete_charter_doc
    	@image_delete ||= "0"
	end

	def delete_charter_doc=(value)
		@image_delete = value
	end
	
	def delete_pert_file
    	@image_delete ||= "0"
	end

	def delete_pert_file=(value)
		@image_delete = value
	end

	private
		def destroy_files?
			self.charter_doc.clear if @delete_charter_doc == "1"
			self.pert_file.clear if @delete_pert_file == "1"
		end
	
end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base

  ROLES = ['Patrocinador', 'Elaborado por', 'Autorizado por','Cliente', 'Lider de Proyecto']

  belongs_to :user
  belongs_to :charter
  has_one :contacto, :as => :contactable
end

app/controllers/charters_controller.rb
class ChartersController < ApplicationController
  # GET /charters
  # GET /charters.xml
  def index
    @charters = Charter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @charters }
    end
  end

  # GET /charters/1
  # GET /charters/1.xml
  def show
    @charter = Charter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @charter }
    end
  end

  # GET /charters/new
  # GET /charters/new.xml
  def new
    @charter = Charter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @charter }
    end
  end

  # GET /charters/1/edit
  def edit
    @charter = Charter.find(params[:id])
  end

  # POST /charters
  # POST /charters.xml
  def create
    @charter = Charter.new(params[:charter])

    respond_to do |format|
      if @charter.save
        format.html { redirect_to(@charter, :notice => 'Charter was successfully created.') }
        format.xml  { render :xml => @charter, :status => :created, :location => @charter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @charter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /charters/1
  # PUT /charters/1.xml
  def update
    @charter = Charter.find(params[:id])

    respond_to do |format|
      if @charter.update_attributes(params[:charter])
        format.html { redirect_to(@charter, :notice => 'Charter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @charter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /charters/1
  # DELETE /charters/1.xml
  def destroy
    @charter = Charter.find(params[:id])
    @charter.destroy

    respond_to do |format|
      format.html { redirect_to(charters_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  # GET /milestones
  # GET /milestones.xml
  def index
    @milestones = Milestone.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @milestones }
    end
  end

  # GET /milestones/1
  # GET /milestones/1.xml
  def show
    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @milestone }
    end
  end

  # GET /milestones/new
  # GET /milestones/new.xml
  def new
    @milestone = Milestone.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @milestone }
    end
  end

  # GET /milestones/1/edit
  def edit
    @milestone = Milestone.find(params[:id])
  end

  # POST /milestones
  # POST /milestones.xml
  def create
    @milestone = Milestone.new(params[:milestone])

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to(@milestone, :notice => 'Milestone was successfully created.') }
        format.xml  { render :xml => @milestone, :status => :created, :location => @milestone }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @milestone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /milestones/1
  # PUT /milestones/1.xml
  def update
    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      if @milestone.update_attributes(params[:milestone])
        format.html { redirect_to(@milestone, :notice => 'Milestone was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @milestone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.xml
  def destroy
    @milestone = Milestone.find(params[:id])
    @milestone.destroy

    respond_to do |format|
      format.html { redirect_to(milestones_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sphinx_controller.rb
class SphinxController < ApplicationController

  def contacto
  	if params[:q]
	  	_personas = Persona.includes(:contacto).where(['nombre LIKE :q OR ap_paterno LIKE :q OR ap_materno LIKE :q', {:q => "%#{params[:q]}%"}]).order('nombre').all
	  	@data = _personas.map{|x| x.attributes.merge({:contacto=>x.contacto.attributes}) }
	end
	
	respond_to do |format|
		format.json{ render :json=>@data.as_json }
	end
	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charters_helper.rb
module ChartersHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/sphinx_helper.rb
module SphinxHelper
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/milestones/_form.html.erb
<%= form_for(@milestone) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :fecha_inicio %><br />
    <%= f.datetime_select :fecha_inicio %>
  </div>
  <div class="field">
    <%= f.label :entregable %><br />
    <%= f.text_field :entregable %>
  </div>
  <div class="field">
    <%= f.label :charter %><br />
    <%= f.text_field :charter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<h1>Editing milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', milestones_path %>

app/views/milestones/index.html.erb
<h1>Listing milestones</h1>

<table>
  <tr>
    <th>Descripcion</th>
    <th>Fecha inicio</th>
    <th>Entregable</th>
    <th>Charter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @milestones.each do |milestone| %>
  <tr>
    <td><%= milestone.descripcion %></td>
    <td><%= milestone.fecha_inicio %></td>
    <td><%= milestone.entregable %></td>
    <td><%= milestone.charter %></td>
    <td><%= link_to 'Show', milestone %></td>
    <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
    <td><%= link_to 'Destroy', milestone, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Milestone', new_milestone_path %>

app/views/milestones/new.html.erb
<h1>New milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripcion:</b>
  <%= @milestone.descripcion %>
</p>

<p>
  <b>Fecha inicio:</b>
  <%= @milestone.fecha_inicio %>
</p>

<p>
  <b>Entregable:</b>
  <%= @milestone.entregable %>
</p>

<p>
  <b>Charter:</b>
  <%= @milestone.charter %>
</p>


<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', milestones_path %>