config/routes.rb
Gestor::Application.routes.draw do

  get "sphinx/contacto"
  resources :empresas

  resources :personas

  get "home/index"

  resources :proyectos do
  	resources :objetivo_negocios
  	resources :milestones
  end

   root :to => "home#index"

end

app/models/charter.rb
class Charter < ActiveRecord::Base
	has_many :objetivo_negocios, :dependent => :destroy
	has_many :charter_contactos
	has_many :contactos, :through => :charter_contactos	
	belongs_to :proyecto
	
	accepts_nested_attributes_for :charter_contactos, :allow_destroy => true
end

app/models/charter_contacto.rb
class CharterContacto < ActiveRecord::Base

  ROLES = ['Sponsor', 'Preparado por', 'Cliente', 'Administrador de programa', 'Lider de Proyecto'].sort!

  belongs_to :charter
  belongs_to :contacto
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  belongs_to :contactable, :polymorphic => true
  belongs_to :identificable, :polymorphic => true
end

app/models/elemento_estrategico.rb
class ElementoEstrategico < ActiveRecord::Base
  belongs_to :objetivoNegocio
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_one :contacto, :as => :identificable
	
	
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :charter
end

app/models/objetivo_negocio.rb
class ObjetivoNegocio < ActiveRecord::Base
  belongs_to :charter
  has_many :elemento_estrategicos, :dependent => :destroy
  
  accepts_nested_attributes_for :elemento_estrategicos, :allow_destroy => true
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_one :contacto, :as => :identificable
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
	include Permalynkable
	extend Permalynkable::ClassMethods
	
	attr_accessible :delete_charter_doc, :delete_pert_file

	has_one :charter, :dependent => :destroy
	accepts_nested_attributes_for :charter
	
	has_attached_file :charter_doc
	has_attached_file :pert_file
	
	before_save :destroy_files?

	def delete_charter_doc
    	@image_delete ||= "0"
	end

	def delete_charter_doc=(value)
		@image_delete = value
	end
	
	def delete_pert_file
    	@image_delete ||= "0"
	end

	def delete_pert_file=(value)
		@image_delete = value
	end

	private
		def destroy_files?
			self.charter_doc.clear if @delete_charter_doc == "1"
			self.pert_file.clear if @delete_pert_file == "1"
		end
	
end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base

  ROLES = ['Patrocinador', 'Elaborado por', 'Autorizado por','Cliente', 'Lider de Proyecto']

  belongs_to :user
  belongs_to :charter
  has_one :contacto, :as => :contactable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/objetivo_negocios_controller.rb
class ObjetivoNegociosController < ApplicationController
  before_filter :find_proyecto

  # GET /objetivo_negocios
  # GET /objetivo_negocios.xml
  def index
    @objetivo_negocios = ObjetivoNegocio.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @objetivo_negocios }
    end
  end

  # GET /objetivo_negocios/1
  # GET /objetivo_negocios/1.xml
  def show
    @objetivo_negocio = ObjetivoNegocio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @objetivo_negocio }
    end
  end

  # GET /objetivo_negocios/new
  # GET /objetivo_negocios/new.xml
  def new
    @objetivo_negocio = ObjetivoNegocio.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @objetivo_negocio }
    end
  end

  # GET /objetivo_negocios/1/edit
  def edit
    @objetivo_negocio = ObjetivoNegocio.find(params[:id])
  end

  # POST /objetivo_negocios
  # POST /objetivo_negocios.xml
  def create
    @objetivo_negocio = ObjetivoNegocio.new(params[:objetivo_negocio])
    @objetivo_negocio.charter_id = @proyecto.charter.id
    respond_to do |format|
      if @objetivo_negocio.save
        format.html { redirect_to(proyecto_objetivo_negocio_path(@proyecto, @objetivo_negocio), :notice => 'Objetivo negocio was successfully created.') }
        format.xml  { render :xml => @objetivo_negocio, :status => :created, :location => @objetivo_negocio }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @objetivo_negocio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /objetivo_negocios/1
  # PUT /objetivo_negocios/1.xml
  def update
    @objetivo_negocio = ObjetivoNegocio.find(params[:id])

    respond_to do |format|
      if @objetivo_negocio.update_attributes(params[:objetivo_negocio])
        format.html { redirect_to([@proyecto, @objetivo_negocio], :notice => 'Objetivo negocio was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @objetivo_negocio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /objetivo_negocios/1
  # DELETE /objetivo_negocios/1.xml
  def destroy
    @objetivo_negocio = ObjetivoNegocio.find(params[:id])
    @objetivo_negocio.destroy

    respond_to do |format|
      format.html { redirect_to(proyecto_objetivo_negocios_url([@proyecto])) }
      format.xml  { head :ok }
    end
  end
  
  protected
  
  def find_proyecto
  	@proyecto = Proyecto.includes(:charter).exfind(params[:proyecto_id])
  end
end

app/controllers/sphinx_controller.rb
class SphinxController < ApplicationController

  def contacto
  	if params[:q]
	  	_personas = Persona.includes(:contacto).where(['nombre LIKE :q OR ap_paterno LIKE :q OR ap_materno LIKE :q', {:q => "%#{params[:q]}%"}]).order('nombre').all
	  	@data = _personas.map{|x| x.attributes.merge({:contacto=>x.contacto.attributes}) }
	end
	
	respond_to do |format|
		format.json{ render :json=>@data.as_json }
	end
	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charters_helper.rb
module ChartersHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/objetivo_negocios_helper.rb
module ObjetivoNegociosHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/sphinx_helper.rb
module SphinxHelper
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/objetivo_negocios/_form.html.erb
<%= nested_form_for([@proyecto, @objetivo_negocio]) do |f| %>
  <% if @objetivo_negocio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@objetivo_negocio.errors.count, "error") %> prohibited this objetivo_negocio from being saved:</h2>

      <ul>
      <% @objetivo_negocio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :texto %><br />
    <%= f.text_field :texto %>
  </div>
  
  <div class="fields">
  	<%= f.fields_for :elemento_estrategicos do |elem_form|  %>
  		<%= elem_form.label :texto %> <%= elem_form.text_field :texto %>
  		<%= elem_form.link_to_remove "Remove this elemento" %>
  	<% end %>
  	<p><%= f.link_to_add "Add a elemento", :elemento_estrategicos %></p>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objetivo_negocios/edit.html.erb
<h1>Editing objetivo_negocio</h1>

<%= render 'form' %>

<%= link_to 'Show', [@proyecto, @objetivo_negocio] %> |
<%= link_to 'Back', proyecto_objetivo_negocios_path([@proyecto]) %>

app/views/objetivo_negocios/index.html.erb
<h1><%= @proyecto.charter.proyecto_titulo %> <small>Objetivos del Negocio</small></h1>
<p>
	<%= link_to 'Nuevo Objetivo', new_proyecto_objetivo_negocio_path, :class=>'btn btn-primary pull-right' %>
</p>
<table class="table">
<thead>
  <tr>
    <th>Objetivo del Negocio</th>
  </tr>
</thead>
<tbody>
<% @objetivo_negocios.each do |objetivo_negocio| %>
  <tr>
    <td><%= link_to objetivo_negocio.texto, [@proyecto, objetivo_negocio] %></td>
    <td>
    	<div class="btn-group pull-right">
		<%= link_to '#', :class=>"btn dropdown-toggle", :'data-toggle'.to_sym=>"dropdown" do  %>
		    Acciones
    		<span class="caret"></span>
  		<% end %>
  		<ul class="dropdown-menu">
    		<li><%= link_to 'Editar', edit_proyecto_objetivo_negocio_path(@proyecto, objetivo_negocio) %></li>
    		<li><%= link_to 'Eliminar', [@proyecto, objetivo_negocio], :confirm => 'Are you sure?', :method => :delete %></li>
	 	</ul>
		</div>
    </td>
  </tr>
<% end %>
</tbody>
</table>

<br />

app/views/objetivo_negocios/new.html.erb
<h1>New objetivo_negocio</h1>

<%= render 'form' %>

<%= link_to 'Back', proyecto_objetivo_negocios_path(@proyecto) %>

app/views/objetivo_negocios/show.html.erb
<h1><%= @proyecto.charter.proyecto_titulo %> <small>Objetivo del Negocio</small></h1>
<% if notice%>
<div class="alert alert-block">
  <a class="close" data-dismiss="alert">×</a>
  <p id="notice"><%= notice %></p>
</div>
<%end%>

<p>
  <b>Texto:</b>
  <%= @objetivo_negocio.texto %>
</p>

<div class="page-header">
    <h3>Elementos Estratégicos</h3>
</div>

<table class="table">
	<thead>
		<tr>
			<th>Texto</th>
		</tr>
	</thead>
	<tbody>
	<% @objetivo_negocio.elemento_estrategicos do |e| %>
		<tr>
			<td><%= e.texto %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<div class="form-actions">
	<%= link_to 'Regresar', proyecto_objetivo_negocios_path([@proyecto]), :class=>'btn' %>
	<div class="pull-right">
		<%= link_to 'Editar', edit_proyecto_objetivo_negocio_path(@proyecto, @objetivo_negocio), :class=>'btn' %>
		<%= link_to 'Eliminar', proyecto_objetivo_negocio_path(@proyecto, @objetivo_negocio), :class=>'btn btn-danger', :confirm => 'Are you sure?', :method => :delete %>
	</div>
</div>