config/routes.rb
Gestor::Application.routes.draw do

  get "sphinx/contacto"
  resources :empresas

  resources :personas

  get "home/index"

  resources :proyectos do
  	resources :objetivo_negocios
  	resources :milestones
  end

   root :to => "home#index"

end

app/models/charter.rb
class Charter < ActiveRecord::Base
	has_many :objetivo_negocios, :dependent => :destroy
	has_many :charter_contactos
	has_many :contactos, :through => :charter_contactos	
	belongs_to :proyecto
	
	accepts_nested_attributes_for :charter_contactos, :allow_destroy => true
end

app/models/charter_contacto.rb
class CharterContacto < ActiveRecord::Base

  ROLES = ['Sponsor', 'Preparado por', 'Cliente', 'Administrador de programa', 'Lider de Proyecto'].sort!

  belongs_to :charter
  belongs_to :contacto
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  belongs_to :contactable, :polymorphic => true
  belongs_to :identificable, :polymorphic => true
end

app/models/elemento_estrategico.rb
class ElementoEstrategico < ActiveRecord::Base
  belongs_to :objetivoNegocio
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	has_one :contacto, :as => :identificable
	
	
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :charter
end

app/models/objetivo_negocio.rb
class ObjetivoNegocio < ActiveRecord::Base
  belongs_to :charter
  has_many :elemento_estrategicos, :dependent => :destroy
  
  accepts_nested_attributes_for :elemento_estrategicos, :allow_destroy => true
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_one :contacto, :as => :identificable
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
	include Permalynkable
	extend Permalynkable::ClassMethods
	
	attr_accessible :delete_charter_doc, :delete_pert_file

	has_one :charter, :dependent => :destroy
	accepts_nested_attributes_for :charter
	
	has_attached_file :charter_doc
	has_attached_file :pert_file
	
	before_save :destroy_files?

	def delete_charter_doc
    	@image_delete ||= "0"
	end

	def delete_charter_doc=(value)
		@image_delete = value
	end
	
	def delete_pert_file
    	@image_delete ||= "0"
	end

	def delete_pert_file=(value)
		@image_delete = value
	end

	private
		def destroy_files?
			self.charter_doc.clear if @delete_charter_doc == "1"
			self.pert_file.clear if @delete_pert_file == "1"
		end
	
end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base

  ROLES = ['Patrocinador', 'Elaborado por', 'Autorizado por','Cliente', 'Lider de Proyecto']

  belongs_to :user
  belongs_to :charter
  has_one :contacto, :as => :contactable
end

app/controllers/charters_controller.rb
class ChartersController < ApplicationController
  # GET /charters
  # GET /charters.xml
  def index
    @charters = Charter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @charters }
    end
  end

  # GET /charters/1
  # GET /charters/1.xml
  def show
    @charter = Charter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @charter }
    end
  end

  # GET /charters/new
  # GET /charters/new.xml
  def new
    @charter = Charter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @charter }
    end
  end

  # GET /charters/1/edit
  def edit
    @charter = Charter.find(params[:id])
  end

  # POST /charters
  # POST /charters.xml
  def create
    @charter = Charter.new(params[:charter])

    respond_to do |format|
      if @charter.save
        format.html { redirect_to(@charter, :notice => 'Charter was successfully created.') }
        format.xml  { render :xml => @charter, :status => :created, :location => @charter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @charter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /charters/1
  # PUT /charters/1.xml
  def update
    @charter = Charter.find(params[:id])

    respond_to do |format|
      if @charter.update_attributes(params[:charter])
        format.html { redirect_to(@charter, :notice => 'Charter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @charter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /charters/1
  # DELETE /charters/1.xml
  def destroy
    @charter = Charter.find(params[:id])
    @charter.destroy

    respond_to do |format|
      format.html { redirect_to(charters_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  # GET /empresas
  # GET /empresas.xml
  def index
    @empresas = Empresa.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.xml
  def show
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.xml
  def new
    @empresa = Empresa.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.xml
  def create
    @empresa = Empresa.new(params[:empresa])

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to(@empresa, :notice => 'Empresa was successfully created.') }
        format.xml  { render :xml => @empresa, :status => :created, :location => @empresa }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @empresa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.xml
  def update
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to(@empresa, :notice => 'Empresa was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @empresa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.xml
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to(empresas_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/sphinx_controller.rb
class SphinxController < ApplicationController

  def contacto
  	if params[:q]
	  	_personas = Persona.includes(:contacto).where(['nombre LIKE :q OR ap_paterno LIKE :q OR ap_materno LIKE :q', {:q => "%#{params[:q]}%"}]).order('nombre').all
	  	@data = _personas.map{|x| x.attributes.merge({:contacto=>x.contacto.attributes}) }
	end
	
	respond_to do |format|
		format.json{ render :json=>@data.as_json }
	end
	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charters_helper.rb
module ChartersHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/sphinx_helper.rb
module SphinxHelper
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/charters/_form.html.erb
<%= form_for(@charter) do |f| %>
  <% if @charter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charter.errors.count, "error") %> prohibited this charter from being saved:</h2>

      <ul>
      <% @charter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proyecto_titulo %><br />
    <%= f.text_field :proyecto_titulo %>
  </div>
  <div class="field">
    <%= f.label :proyecto_version %><br />
    <%= f.text_field :proyecto_version %>
  </div>
  <div class="field">
    <%= f.label :resumen %><br />
    <%= f.text_area :resumen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charters/edit.html.erb
<h1>Editing charter</h1>

<%= render 'form' %>

<%= link_to 'Show', @charter %> |
<%= link_to 'Back', charters_path %>

app/views/charters/index.html.erb
<h1>Listing charters</h1>

<%= link_to 'New Charter', new_charter_path %>
<table>
  <tr>
    <th>Proyecto titulo</th>
    <th>Proyecto version</th>
    <th>Resumen</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @charters.each do |charter| %>
  <tr>
    <td><%= charter.proyecto_titulo %></td>
    <td><%= charter.proyecto_version %></td>
    <td><%= charter.resumen %></td>
    <td><%= link_to 'Show', charter %></td>
    <td><%= link_to 'Edit', edit_charter_path(charter) %></td>
    <td><%= link_to 'Destroy', charter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/charters/new.html.erb
<h1>New charter</h1>

<%= render 'form' %>

<%= link_to 'Back', charters_path %>

app/views/charters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Proyecto titulo:</b>
  <%= @charter.proyecto_titulo %>
</p>

<p>
  <b>Proyecto version:</b>
  <%= @charter.proyecto_version %>
</p>

<p>
  <b>Resumen:</b>
  <%= @charter.resumen %>
</p>


<%= link_to 'Edit', edit_charter_path(@charter) %> |
<%= link_to 'Back', charters_path %>

app/views/empresas/_form.html.erb
<%= simple_form_for(@empresa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :razon %>
    <%= f.input :rfc %>
    <%= f.input :sitioweb %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<h1>Listing empresas</h1>

<table>
  <tr>
    <th>Razon</th>
    <th>Rfc</th>
    <th>Sitioweb</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @empresas.each do |empresa| %>
  <tr>
    <td><%= empresa.razon %></td>
    <td><%= empresa.rfc %></td>
    <td><%= empresa.sitioweb %></td>
    <td><%= link_to 'Show', empresa %></td>
    <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
    <td><%= link_to 'Destroy', empresa, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Razon:</b>
  <%= @empresa.razon %>
</p>

<p>
  <b>Rfc:</b>
  <%= @empresa.rfc %>
</p>

<p>
  <b>Sitioweb:</b>
  <%= @empresa.sitioweb %>
</p>


<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>